# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/blog/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Lemon73-Computing"

[social.params]
icon = "brand-github"

#[[social]]
#identifier = "twitter"
#name = "Twitter"
#url = "https://twitter.com"

#[social.params]
#icon = "brand-twitter"

[[social]]
identifier = "rss"
name = "RSS"
url = "/blog/index.xml"

[social.params]
icon = "rss"
